version: '3.4'

services:
  db:
    container_name: auth_db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: iwos2wHY3fj83djsAZUkKVhlkREs
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_s3cur3_password
      MYSQL_DATABASE: auth_db
    networks:
      - default